[Interface]
# Клиент WireGuard
PrivateKey = aCK7DNDfJs2NPIcnHMrC0PdseubjQqrRYkQZ8n8ORHg=
Address = 10.10.0.2/24
DNS = 1.1.1.1

[Peer]
# Сервер (Windows PC)
PublicKey = dOB97MKJ0ZZMYVkqjnDtzJ22cAJlxrnoCzenhp7It3U=
PresharedKey = Lh93CCygMMe2SE0OEf9QXaWJ5Oas8G9Dve/DhEyeux0=
Endpoint = 95.174.126.186:51820
AllowedIPs = 10.10.0.1/32
PersistentKeepalive = 25
