[Interface]
# Server — Windows PC
PrivateKey = yEvyzdOd8Gsf0Je5bjfLVmvHczRJ3vGzL7fidsDurWg=
Address = 10.10.0.1/24
ListenPort = 51820

[Peer]
# OpenWrt client
PublicKey = 0dmPvu+/C7xujdTl6nWGOkjylmcnHs9V+w4ZzHfl+Ds=
PresharedKey = 2TjIeMwB13kir235UluJjqcncB4V646n/1vy1bJ9PDM=
AllowedIPs = 10.10.0.2/32
